### ISSUE TITLE
Missed transform between base_link and imu_link

### ISSUE THREAD

**Issue by brianzhan** [clearpathrobotics/imu_compass#3]
Hi, I have the error message: Missed transform between base_link and imu_link

I am using the UM6r2, and launched my UM6r2 with the UM6 ROS package. Was wondering if there is a solution for this?

**Comment by paulbovbel** [comment]
Hi @brianzhan, this package is legacy and unmaintained.

For fusing IMU data into a pose estimate, I would point you at imu_filter_madgwick. Please see the husky or jackal URDF/tf trees, and controls bringup to see how this is implemented.

**Comment by brianzhan** [comment]
I see, thank you very much!

**Comment by brianzhan** [comment]
I was wondering if you might be able to go into a bit more detail into how I might use that Husky package to filter my UM6 information? I found the following folder, but can't seem to figure out how to use it to filter my IMU. https://github.com/husky/husky_robot/tree/f3d3f10f5a9dd4b0517f9de7cbd31de974fe53ff/husky_bringup/scripts

**Comment by paulbovbel** [comment]
Look at the way the um6 pipeline is set up https://github.com/husky/husky_robot/blob/f3d3f10f5a9dd4b0517f9de7cbd31de974fe53ff/husky_bringup/launch/um6_config/um6.launch

**Comment by brianzhan** [comment]
Thanks! I'm not sure how to modify this line in that code? 
<rosparam file="$(env HUSKY_MAG_CONFIG)" />

I am using the UM6 with your UM6 ROS package

**Comment by brianzhan** [comment]
My interpretation was that this code should set HUSKY_MAG_CONFIG,https://github.com/husky/husky_robot/blob/indigo-devel/husky_bringup/CMakeLists.txt. (I ran this code by cloning the husky_robots directory, adding husky_bringup directory into the src folder, then calling catkin_make)

When I then try calling um6.launch, I get the following bug message: environment variable 'HUSKY_MAG_CONFIG' is not set

**Comment by brianzhan** [comment]
Thanks a lot! Finally got it running. I was wondering: am I correct to assume the ideal way to calibrate the compass to rotate it repeatedly, along (in my case, the) one axis that I want the magnetometer to measure? And I'd assume precision of the spin around one point without xyz-movement is necessary?
